spring:
  h2.console.enabled: true
  # H2 데이터베이스 웹 콘솔을 활성화 (http://localhost:8080/h2-console)

  datasource:
    url: jdbc:h2:mem:boarddb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    # H2 데이터베이스 연결 URL
    # mem:boarddb → 메모리 모드의 boarddb라는 DB 사용
    # DB_CLOSE_DELAY=-1 → 연결이 모두 닫혀도 DB를 종료하지 않음 (앱이 살아있는 동안 유지)
    # DB_CLOSE_ON_EXIT=FALSE → JVM 종료 시에도 DB를 닫지 않음 (테스트나 개발 시 유용)

    driver-class-name: org.h2.Driver
    # H2 데이터베이스 드라이버 클래스

    username: sa
    # 기본 사용자명 (H2의 기본 계정)

    password:
    # 비밀번호 (기본은 빈 값)

  jpa:
    hibernate.ddl-auto: update
    # JPA가 DB 테이블을 자동으로 생성 또는 업데이트
    # 엔티티 클래스 변경 시 테이블 구조를 자동으로 반영 (데이터는 유지됨)

    defer-datasource-initialization: true
    # H2 콘솔과 초기화 스크립트를 함께 사용할 때 필요

  server:
    port: 8080
    # 애플리케이션 서버가 실행될 포트 번호 (기본값이지만 명시적으로 지정)

